name: Test and Deploy

on:
  # Enable these triggers when finalized
  push:
    branches: [feature/gh-actions]
  # branches: [ main ]
  
  # pull_request:
  #   branches: [ main ]

  # Manual trigger
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./minitwit/Api
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./minitwit/Api
    - name: Test
      working-directory: ./minitwit/Api
      run: dotnet test --no-build --verbosity normal
      
  build-publish-image:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v2
    - name: Publish
      run: dotnet publish -c Release -o ./publish
      working-directory: ./minitwit/Api
    - name: Set up Docker Builder
      uses: docker/setup-buildx-action@v1
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}
        context: ./minitwit/Api
        tag_with_sha: true
        tag_with_ref: true
    
