name: CI/CD (Test, Containerize, Deploy)

on:
  # Enable these triggers when finalized
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./minitwit/Api
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./minitwit/Api
    - name: Publish
      run: dotnet publish -c Release -o ./publish
      working-directory: ./minitwit/Api
    # - name: Test
    #   working-directory: ./minitwit/Api
    #   run: dotnet test --no-build --verbosity normal
